insert into public.facilities (
  slug,
  name,
  status,
  latitude,
  longitude,
  address,
  municipality,
  region,
  boarding_modes,
  description_short,
  monthly_price_sek,
  has_riding_house,
  has_paddock,
  open_spots,
  source_label
) values
  (
    'ekbacken-ridgard',
    'Ekbacken Ridgard',
    'verified',
    59.8581,
    17.8203,
    'Funbo-Lovsta 24, Uppsala',
    'Uppsala',
    'Uppsala lan',
    '{"box"}',
    'Verifierad anlaggning med 24 boxplatser, ridhus, paddock och tydliga foder- och hagrutiner.',
    4650,
    true,
    true,
    2,
    'Claimed profile'
  ),
  (
    'norrhage-loosdrift',
    'Norrhage Loosdrift',
    'auto_listed',
    59.5594,
    18.0891,
    'Angarns-Lundby 7, Vallentuna',
    'Vallentuna',
    'Stockholms lan',
    '{"loose"}',
    'Automatiskt listad anlaggning med fokus pa flock och stora vinterhagar.',
    3500,
    false,
    true,
    4,
    'OSM import'
  ),
  (
    'soderasens-sportstall',
    'Soderasens Sportstall',
    'verified',
    56.1334,
    13.1226,
    'Vedbyvagen 12, Klippan',
    'Klippan',
    'Skane lan',
    '{"box","loose"}',
    'Sportstall med bade box och mindre losdriftsgrupp, paddock och ridhus.',
    5200,
    true,
    true,
    1,
    'Claimed profile'
  );
